### PR TITLE
add first mention of person when about=person

### PR DESCRIPTION
**Pull request by kitkat119**
When an article is classified as about a person, it outputs the first sentence mentioning the person. One issue is that this might be the same as the first sentence!

### CODE REVIEW

**Comment by railsagainstignorance** [comment]
It works for me.

**Comment by railsagainstignorance** [comment]
I reckon it might be worth expanding this to list all mentions of the about:PERSON.

**Comment by kitkat119** [comment]
Another e.g. of about=person with >1 full name mention is 9697dd94-430a-11e8-803a-295c97e6fd0b

**Comment by railsagainstignorance** [comment]
LGTM

**Pull request merged**
